plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

locale: en_AU

url: "http://www.shavon.gg" 

collections:
  post_tags:
    permalink: /tags/:name/
    output: true

defaults:
  - scope:
      path: ''
      type: post_tags
    values:
      permalink: "/tags/:name/"
      layout: tag